# fly.toml app configuration file generated for bootcamp-2025-bacen-service on 2025-03-30T22:21:53-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bootcamp-2025-bacen-service'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  # auto_stop_machines = 'stop'
  # auto_start_machines = true
  auto_stop_machines = "timeout"
  auto_start_machines = true  
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
