name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build e Testes com Maven
      run: mvn clean install
  
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build da imagem Docker
      run: docker build -t viniciusnavarro2/bacen-service:latest .

    - name: Push da imagem para o Docker Hub
      run: docker push viniciusnavarro2/bacen-service:latest
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Deploy no Fly.io
        uses: superfly/flyctl-actions@1.4
        with:
          args: "deploy --config fly.toml"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    